CREATE TABLE IF NOT EXISTS "portfolio_hosting" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "portfolio_hosting_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"desc" varchar(255) NOT NULL,
	"tags" varchar(255) NOT NULL
);
