CREATE TABLE IF NOT EXISTS "portfolio_project" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "portfolio_project_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"url" varchar(500) NOT NULL,
	"desc" varchar(255) NOT NULL,
	"websitelink" varchar(255) NOT NULL,
	"githublink" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
