CREATE TABLE IF NOT EXISTS "portfolio_like" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "portfolio_like_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"comment_id" integer NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "portfolio_like" ADD CONSTRAINT "portfolio_like_comment_id_portfolio_comment_id_fk" FOREIGN KEY ("comment_id") REFERENCES "public"."portfolio_comment"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "portfolio_like" ADD CONSTRAINT "portfolio_like_user_id_portfolio_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."portfolio_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
