import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { SessionProvider } from "next-auth/react";
import Home from "~/components/home";
import AnimatedCircles from "~/components/animated-circles";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body
        style={{
          backgroundImage:
            "linear-gradient(90deg, #444 2px, transparent 0), linear-gradient(180deg, #444 2px, transparent 0)",
          backgroundSize: "5vh 5vh",
          backgroundColor: "rgb(61, 61, 61)",
        }}
        className="min-h-screen max-lg:hidden "
      >
        <AnimatedCircles />
        <SessionProvider>
          <TRPCReactProvider>
            <Home>{children}</Home>
          </TRPCReactProvider>
        </SessionProvider>
      </body>
      <TRPCReactProvider>
      <div className="hidden max-lg:block">
        <Home>{children}</Home>
      </div>
      </TRPCReactProvider>
    </html>
  );
}
